# ==============================================================================
# SonarQube Scanner Configuration - Backend MediBloc
# Auteur : SINGO Yao Dieu Donne
# Date   : 2026-09-17
# ==============================================================================

# Identifiants du projet
sonar.projectKey=medibloc-backend
sonar.projectName=MediBloc Backend
sonar.projectVersion=1.0.0

# Chemins des sources et des tests
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts,test/**/*.spec.ts

# Encodage du code source
sonar.sourceEncoding=UTF-8

# Exclusions de couverture et d'analyse
sonar.exclusions=**/.env,**/.env.*,**/node_modules/**,**/dist/**,**/logs/**,**/coverage/**,**/prisma/migrations/**
sonar.security.excludes=**/.env,**/.env.*

# Integration des rapports de couverture LCOV
sonar.javascript.lcov.reportPaths=coverage/lcov.info
