blank_issues_enabled: false
contact_links:
  - name: Guide et Documentation MediBloc
    url: https://github.com/Singosirutonamikaze/medibloc_new_version
    about: Consultez la documentation du projet avant d'ouvrir un ticket.
